# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: causal_labels.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="causal_labels.proto",
    package="waymo.causal_agents",
    syntax="proto2",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x13\x63\x61usal_labels.proto\x12\x13waymo.causal_agents"a\n\x0c\x43\x61usalLabels\x12\x13\n\x0bscenario_id\x18\x02 \x01(\t\x12<\n\x0flabeler_results\x18\x01 \x03(\x0b\x32#.waymo.causal_agents.LabelerResults"*\n\x0eLabelerResults\x12\x18\n\x10\x63\x61usal_agent_ids\x18\x01 \x03(\t',
)


_CAUSALLABELS = _descriptor.Descriptor(
    name="CausalLabels",
    full_name="waymo.causal_agents.CausalLabels",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="scenario_id",
            full_name="waymo.causal_agents.CausalLabels.scenario_id",
            index=0,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="labeler_results",
            full_name="waymo.causal_agents.CausalLabels.labeler_results",
            index=1,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=141,
)


_LABELERRESULTS = _descriptor.Descriptor(
    name="LabelerResults",
    full_name="waymo.causal_agents.LabelerResults",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="causal_agent_ids",
            full_name="waymo.causal_agents.LabelerResults.causal_agent_ids",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=143,
    serialized_end=185,
)

_CAUSALLABELS.fields_by_name["labeler_results"].message_type = _LABELERRESULTS
DESCRIPTOR.message_types_by_name["CausalLabels"] = _CAUSALLABELS
DESCRIPTOR.message_types_by_name["LabelerResults"] = _LABELERRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CausalLabels = _reflection.GeneratedProtocolMessageType(
    "CausalLabels",
    (_message.Message,),
    {
        "DESCRIPTOR": _CAUSALLABELS,
        "__module__": "causal_labels_pb2",
        # @@protoc_insertion_point(class_scope:waymo.causal_agents.CausalLabels)
    },
)
_sym_db.RegisterMessage(CausalLabels)

LabelerResults = _reflection.GeneratedProtocolMessageType(
    "LabelerResults",
    (_message.Message,),
    {
        "DESCRIPTOR": _LABELERRESULTS,
        "__module__": "causal_labels_pb2",
        # @@protoc_insertion_point(class_scope:waymo.causal_agents.LabelerResults)
    },
)
_sym_db.RegisterMessage(LabelerResults)


# @@protoc_insertion_point(module_scope)
