"""This script analyzes the categorical distributions of the training, validation and testing splits of pre-cached (h5)
data subsets by generating distribution heatmaps. It helps understand and study whether there is a distribution shift
between the subsets.
"""

import argparse
from pathlib import Path

import h5py
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from numpy.typing import NDArray


def _get_agent_scores_from_h5(group: h5py.File) -> tuple[NDArray[np.int_], NDArray[np.int_]]:
    """Extract individual and interaction agent scores from an h5py group.

    NOTE: this assumes the group was generated by the dataset classes in 'src/scenetokens/datasets'.

    Args:
        group (h5py.File): The h5py group to extract the agent scores from.

    Returns:
        tuple[NDArray[np.int_], NDArray[np.int_]]: A tuple containing arrays of individual and interaction agent scores.
    """
    individual_scores = []
    interaction_scores = []
    for key in group:
        if "individual_agent_scores" not in group[key] or "interaction_agent_scores" not in group[key]:  # pyright: ignore[reportOperatorIssue]
            continue
        ind_scores = group[key]["individual_agent_scores"][:].squeeze(-1).squeeze(-1)  # pyright: ignore[reportIndexIssue, reportAttributeAccessIssue]
        individual_scores.append(ind_scores)

        int_scores = group[key]["interaction_agent_scores"][:].squeeze(-1).squeeze(-1)  # pyright: ignore[reportIndexIssue, reportAttributeAccessIssue]
        interaction_scores.append(int_scores)
    return np.concatenate(individual_scores, axis=0).astype(int), np.concatenate(interaction_scores, axis=0).astype(int)


def _compute_score_heatmap(h5_files: list[Path]) -> NDArray[np.int_]:
    """Compute a heatmap of agent scores.

    Args:
        h5_files (list[Path]): List of paths to h5 files.

    Returns:
        NDArray[np.int_]: A 2D array representing the heatmap of agent scores.
    """
    full_individual_scores = []
    full_interaction_scores = []
    for h5_file in h5_files:
        print(f"Processing file: {h5_file}")
        with h5py.File(h5_file, "r") as group:
            individual_scores, interaction_scores = _get_agent_scores_from_h5(group)
            full_individual_scores.append(individual_scores)
            full_interaction_scores.append(interaction_scores)

    full_individual_scores = np.concatenate(full_individual_scores, axis=0).astype(int)
    full_interaction_scores = np.concatenate(full_interaction_scores, axis=0).astype(int)
    heatmap = np.zeros((full_individual_scores.max() + 1, full_interaction_scores.max() + 1), dtype=int)
    for ind_score, int_score in zip(full_individual_scores, full_interaction_scores, strict=False):
        heatmap[ind_score, int_score] += 1
    return heatmap


def plot_agent_score_distributions(data_cache_path: Path, data_subsets: list[str], output_path: Path) -> None:
    """Visualizes the agent score distributions for different data subsets as categorical heatmaps.

    Args:
        data_cache_path (Path): Path to the data cache.
        data_subsets (list[str]): List of data subsets to analyze.
        output_path (Path): Path to save the analysis results.
    """
    output_path.mkdir(parents=True, exist_ok=True)

    for data_subset in data_subsets:
        subset_path = data_cache_path / data_subset
        print(f"Analyzing distribution shift for subset: {data_subset} at {subset_path}")

        h5_files = list(subset_path.glob("*.h5"))
        print(f"Found {len(h5_files)} h5 files")

        heatmap = _compute_score_heatmap(h5_files)

        sns.heatmap(
            heatmap,
            annot=True,
            fmt="d",
            cmap="rocket_r",
            linewidths=0.5,
            linecolor="black",
            cbar_kws={"label": "Number of Agents"},
            annot_kws={"fontsize": 6},
        )
        plt.xlabel("Interaction Agent Scores")
        plt.ylabel("Individual Agent Scores")
        plt.title(f"Agent Scores Heatmap for Subset: {data_subset}")
        plt.gca().invert_yaxis()
        plt.tight_layout()

        output_filepath = output_path / f"{data_subset}_heatmap.png"
        plt.savefig(output_filepath, dpi=300)
        plt.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze distribution shift in datasets.")
    parser.add_argument(
        "--data_cache_path", type=Path, default="/data/driving/waymo/data_cache/", help="Path to the data cache."
    )
    parser.add_argument(
        "--data_subsets",
        type=list[str],
        default=["causal-ego-safeshift-training", "causal-ego-safeshift-id", "causal-ego-safeshift-ood"],
        help="List of data subsets to analyze.",
    )
    parser.add_argument(
        "--output_path",
        type=Path,
        default="./out/distribution_shift_analysis/",
        help="Path to save the analysis results.",
    )

    args = parser.parse_args()
    plot_agent_score_distributions(args.data_cache_path, args.data_subsets, args.output_path)
